import { buildLawyerWorkflow } from '../server/lawyerWorkflow';
import { PipelineTracer, STAGE_LABELS } from '../server/pipelineTrace';
declare const process:any;
let pass=0,total=0; const ck=(n:string,v:boolean,d='')=>{total++;if(v)pass++;console.log(`${v?'PASS':'FAIL'} ${n}${d?' :: '+d:''}`)};
const text=`BERITA ACARA PEMERIKSAAN TERSANGKA. Direktur sebuah BPR menyetujui kredit Rp255.000.000 berdasarkan usulan Kabag Kredit. Debitur adalah nasabah existing dan kredit sebelumnya lunas. Tim Kredit bertugas melakukan analisis 5C, survei dan verifikasi dokumen. Pada lembar fiat terdapat catatan cek legalitas kelengkapannya dan opini kepatuhan. Penyidik mempertanyakan kredit tanpa survei ulang, plafond terhadap nilai taksasi agunan, dan pengurangan provisi. Agunan berupa kendaraan dengan BPKB asli dikuasai bank. Sebelum kredit jatuh tempo debitur meminta kredit baru yang lebih besar dan Direktur menolaknya karena repayment capacity tidak memadai. Tidak ada data transaksi yang pada materi ini membuktikan adanya kickback.`;
const evidence={textual_facts:[{statement:'BPKB asli dikuasai bank',page:3},{statement:'Kredit sebelumnya lunas',page:2}],party_claims:[{statement:'Direktur menyetujui berdasarkan usulan Kabag Kredit',page:2}]};
const issues=[{issue:'Apakah persetujuan kredit tanpa survei ulang menunjukkan penyalahgunaan kewenangan?',analysis:'Perlu uji SOP, pembagian tugas Tim Kredit dan approval chain.'},{issue:'Apakah terdapat kesengajaan atau keuntungan pribadi dalam keputusan kredit?',analysis:'Perlu uji aliran manfaat, catatan kehati-hatian dan penolakan pengajuan berikutnya.'},{issue:'Bagaimana posisi agunan dan kerugian yang didalilkan?',analysis:'Perlu uji pengikatan, nilai, eksekutabilitas dan status kerugian.'}];
const actors=[{actor:'Direktur Utama',roles:['Direktur'],pages:[2,3]},{actor:'Kabag Kredit',roles:['Kepala Bagian Kredit'],pages:[2]},{actor:'Tim Kredit',roles:['Account Officer','Legal'],pages:[2]},{actor:'Debitur',roles:['Debitur'],pages:[2,3]},{actor:'Penyidik',roles:['Penyidik'],pages:[1]}];
const adverse=[{analysis:'Penyidik mempertanyakan tidak dilakukannya survei ulang',page:2},{analysis:'Penyidik mempertanyakan rasio plafond terhadap nilai agunan',page:2}];
const gaps=[{gap:'Belum ada data rekening untuk menguji aliran manfaat pribadi.'},{gap:'Belum diverifikasi SOP yang mengatur survei nasabah existing.'}];
const r=buildLawyerWorkflow({title:'Audit',text,sourceRole:'INVESTIGATION_OR_BAP',domainContext:{},evidence,legalIssues:issues,legalGaps:gaps,adverseEvidence:adverse,applicableLaw:[{regulation:'Kandidat hukum',status:'UNVERIFIED'}],verifiedTimeline:[{date:'2022',event:'kredit'}],actorMatrix:actors});
ck('workflow version 1.1',r.version==='1.1',r.version);
ck('criminal orientation is hint not overconfident',r.orientation==='CRIMINAL_DEFENSE'&&r.role_confidence==='MEDIUM',`${r.orientation}/${r.role_confidence}`);
ck('procedural stage investigation',r.procedural_stage==='INVESTIGATION',r.procedural_stage);
ck('10 workflow stages',r.stages.length===10,String(r.stages.length));
ck('allegation matrix issue aligned',r.allegation_response_matrix.length===issues.length,String(r.allegation_response_matrix.length));
ck('counter evidence relevance selective',r.allegation_response_matrix.some(x=>x.counter_material.length>0),'');
ck('authority matrix',r.authority_duty_matrix.length>=4,String(r.authority_duty_matrix.length));
ck('financial audit active',r.financial_collateral_audit.active===true,'');
ck('amount extracted',r.financial_collateral_audit.amounts.some(x=>x.includes('255')),'' );
ck('collateral extracted',r.financial_collateral_audit.collateral_terms.length>0,'');
ck('repayment extracted',r.financial_collateral_audit.repayment_terms.length>0,'');
ck('discrepancy extracted',r.financial_collateral_audit.discrepancy_terms.length>0,'');
ck('document integrity',r.document_integrity_audit.document_markers.length>0,String(r.document_integrity_audit.document_markers.length));
ck('witness categories',r.witness_strategy.witness_targets.some(x=>x.category==='FACT_WITNESS'),'');
ck('procedural actor caution',r.witness_strategy.witness_targets.some(x=>x.category==='PROCEDURAL_ACTOR'&&!!x.caution),'');
ck('expert banking',r.witness_strategy.expert_domains.some(x=>/Perbankan/.test(x)),r.witness_strategy.expert_domains.join('|'));
ck('expert criminal',r.witness_strategy.expert_domains.some(x=>/pidana/.test(x)),r.witness_strategy.expert_domains.join('|'));
ck('stage guarded drafting',r.drafting_plan.some(x=>/pendampingan pemeriksaan/i.test(x.document)&&/Jangan otomatis/.test(x.stage_guard||'')),'');
ck('case theory hypotheses not final conclusions',r.case_theory_candidates.every(x=>/Hipotesis/.test(x)),r.case_theory_candidates.join('|'));
ck('verification queue',r.verification_queue.length>=2,String(r.verification_queue.length));
const tr=new PipelineTracer();tr.begin('ingest');tr.end('ingest','chars=100');tr.begin('lawyer_workflow');tr.end('lawyer_workflow','orientation=CRIMINAL_DEFENSE stage=INVESTIGATION');
ck('pipeline trace lawyer stage exists',Boolean((STAGE_LABELS as any).lawyer_workflow),'');
ck('pipeline trace deterministic labels',tr.summarize().every(x=>!/[A-Z][a-z]+\s+[A-Z][a-z]+/.test(x.label)||x.id==='lawyer_workflow'),tr.summarize().map(x=>x.label).join('|'));
console.log(`\n${pass}/${total} V5.5.1 checks PASS`);if(pass!==total)process.exitCode=1;
